apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cicd-trig
      binding:
        name: binding-cicd
      template:
        name: template-cicd
