apiVersion: v1
kind: Service
metadata:
  labels:
    app: cpat-blog-bff
  name: cpat-blog-bff
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: cpat-blog-bff
