apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cicd-trig
      interceptors:
        - cel:
            filter: "body.push.ref == 'test-ci-cd'"
      binding:
        name: binding-cicd
      template:
        name: template-cicd
