apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cicd-trig
      interceptors:
        - cel:
            filter: "header.match('X-GitHub-Event', 'push')"
            overlays:
            - key: extensions.truncated_sha
              expression: "truncate(body.push.head.sha, 7)"
      binding:
        name: binding-cicd
      template:
        name: template-cicd
