apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cicd-trig
      interceptors:
        - cel:
            filter: "header.canonical('X-GitHub-Event') == body.pull_request.head.branch"
      binding:
        name: binding-cicd
      template:
        name: template-cicd
