apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cpat-blog-client-deployment
    app.kubernetes.io/component: cpat-blog-client
    app.kubernetes.io/instance: cpat-blog-client
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: cpat-blog
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 10-SCL
    version: v1
  name: cpat-blog-client-deployment
spec:
  selector:
    matchLabels:
      app: cpat-blog
      version: v1
  template:
    metadata:
      labels:
        app: cpat-blog
        version: v1
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cpat-blog/cpat-blog-client:32a6732
        envFrom:
        - secretRef:
            name: cpat-blog-secrets
        imagePullPolicy: Always
        name: ui
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 3001
